export { compressSerie } from './compresser'
export { decompressSerie, decompressHeader} from './decompresser'
export { decompressStreaming,  } from './decompressStreaming'
export type { Header } from './Header'
export type {AnyInputSerie, InputStringSerie, DecompressedStringSerie, InputNumberSerie} from './types'